install/profile: nicer git aware prompt

diff --git a/dotfiles/profile b/dotfiles/profile
--- a/dotfiles/profile
+++ b/dotfiles/profile
@@ -15,26 +15,6 @@ shopt -s checkwinsize
 # make less more friendly for non-text input files, see lesspipe(1)
 [ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"
 
-export GITAWAREPROMPT="$HOME/.bash/git-aware-prompt"
-source $GITAWAREPROMPT/main.sh
-
-# set a fancy prompt (non-color, unless we know we "want" color)
-color_prompt="\[$bldgrn\]\u@\h\[$txtrst\]:\[$bldblu\]\w\[$txtrst\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]"
-case "$TERM" in
-xterm-color|xterm-256color)
-    export PS1="$color_prompt"
-    ;;
-xterm)
-    export PS1="$color_prompt"
-    ;;
-screen)
-    export PS1="$color_prompt"
-    ;;
-*)
-    export PS1='\u@\h:\w'
-    ;;
-esac
-
 rand() {
     printf $((  $1 *  RANDOM  / 32767   ))
 }
@@ -49,42 +29,72 @@ rand_element () {
 starts="🌊 ⚡️ ☁️ ⭐️ 🌚 🌝 🌞 🌜 🌍 🌵 🌴 🍄 🎃 💻 📺 🛀 🚽 🛁 🎨 🎬 🎤 🎧 🎶 🎵 👾 🎲 ⚽️ 🏀 🏈 🚴 🏇 🏊 🏄 🏂 ☕️ 🍵 🍺 🍷 🍸 🍕 🍔 🍟 🍣 🍱 🍙 🍜 🍳 🍦 🍧 🍰 🍭 🍒 🍋 🍉 🍑 🍌 🍍 🍆 🏩 🌇 🌆 🏯 🏰 ⛺️ 🌄 🌅 🗽 🌃 🌉 🎢 ⛵️ 🚀 ✈️ 🚁 🚎 🚌 🚕 🚛 🚲 "
 endings="🐶 🐺 🐱 🐭 🐹 🐰 🐸 🐯 🐨 🐻 🐷 🐮 🐗 🐵 🐒 🐴 🐑 🐘 🐼 🐧 🐦 🐤 🐥 🐣 🐔 🐍 🐢 🐛 🐝 🐜 🐞 🐌 🐙 🐠 🐟 🐬 🐳 🐋 🐄 🐏 🐀 🐃 🐅 🐇 🐉 🐎 🐐 🐓 🐕 🐖 🐁 🐂 🐲 🐡 🐊 🐫 🐪 🐆 🐈 🐩 ⛄️ 🙈 🙉 🙊 💀 👽 💩 👾 👻 🎅"
 
-function __prompt_command() {
-    local EXIT="$?"             # This needs to be first
-
-    # Need to call the git branch and dirty fns ourselves, so exit code remains
-    # clean.
-    find_git_branch
-    find_git_dirty
-
-    local RCol='\[\e[0m\]'
-
-    local Red='\[\e[0;31m\]'
-    local Gre='\[\e[0;32m\]'
-    local BYel='\[\e[1;33m\]'
-    local BBlu='\[\e[1;34m\]'
-    local Pur='\[\e[0;35m\]'
-    local Blk='\[\e[0;30m\]'
-
-    local EXIT_STATE=""
-    if [ $EXIT != 0 ]; then
-        EXIT_STATE="${Red}^-- $EXIT${RCol} "
+if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
+    source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
+else
+    if [ -f "$HOME/.bash/git-aware-prompt" ]; then
+        export GITAWAREPROMPT="$HOME/.bash/git-aware-prompt"
+        source $GITAWAREPROMPT/main.sh
     fi
 
-    local EMOJI_START=""
-    local EMOJI_END="$"
-    if [ $(uname -s) == "Darwin" ]; then
-        EMOJI_START="$(rand_element $starts) "
-        EMOJI_END=" $(rand_element $endings)${Blk}¸${RCol}"
-    fi
+    # set a fancy prompt (non-color, unless we know we "want" color)
+    color_prompt="\[$bldgrn\]\u@\h\[$txtrst\]:\[$bldblu\]\w\[$txtrst\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]"
+    case "$TERM" in
+    xterm-color|xterm-256color)
+        export PS1="$color_prompt"
+        ;;
+    xterm)
+        export PS1="$color_prompt"
+        ;;
+    screen)
+        export PS1="$color_prompt"
+        ;;
+    *)
+        export PS1='\u@\h:\w'
+        ;;
+    esac
 
-    local USER_HOST="${Gre}\u${RCol}@${BBlu}\h${RCol}"
-    local DIR_PATH="${BBlu}\w${RCol}"
-    local GIT_STATE="${Pur}\$git_branch${Red}\$git_dirty${RCol}"
+    function __prompt_command() {
+        local EXIT="$?"             # This needs to be first
 
-    PS1="$EMOJI_START$EXIT_STATE$USER_HOST:$DIR_PATH $GIT_STATE$EMOJI_END "
-}
-export PROMPT_COMMAND="__prompt_command"
+        # Need to call the git branch and dirty fns ourselves, so exit code remains
+        # clean.
+        find_git_branch
+        find_git_dirty
+
+        local RCol='\[\e[0m\]'
+
+        local Red='\[\e[0;31m\]'
+        local Gre='\[\e[0;32m\]'
+        local BYel='\[\e[1;33m\]'
+        local BBlu='\[\e[1;34m\]'
+        local Pur='\[\e[0;35m\]'
+        local Blk='\[\e[0;30m\]'
+
+        local EXIT_STATE=""
+        if [ $EXIT != 0 ]; then
+            EXIT_STATE="${Red}^-- $EXIT${RCol} "
+        fi
+
+        local EMOJI_START=""
+        local EMOJI_END="$"
+        if [ $(uname -s) == "Darwin" ]; then
+            EMOJI_START="$(rand_element $starts) "
+            EMOJI_END=" $(rand_element $endings)${Blk}¸${RCol}"
+        fi
+
+        local USER_HOST="${Gre}\u${RCol}@${BBlu}\h${RCol}"
+        local DIR_PATH="${BBlu}\w${RCol}"
+
+        local GIT_STATE=""
+        if [ -f "$HOME/.bash/git-aware-prompt" ]; then
+            GIT_STATE="${Pur}\$git_branch${Red}\$git_dirty${RCol}"
+        fi
+
+        PS1="$EMOJI_START$EXIT_STATE$USER_HOST:$DIR_PATH $GIT_STATE$EMOJI_END "
+    }
+    export PROMPT_COMMAND="__prompt_command"
+fi
 
 #
 # Include private defs (not in main file cuz this one's in my public github).
